---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  remote_user: deploy

  tasks:
    - name: Clone/pull project repo
      git: repo={{ repository }}
           dest={{ install_path }}/{{ project_name }}/app
           accept_hostkey=yes
      notify:
      - restart gunicorn
    
    - name: Delete all .pyc files
      command: find . -name '*.pyc' -delete
      args:
        chdir: "{{ install_path }}/{{ project_name }}/app"
      changed_when: False

    - name: Install python packages
      pip:
        requirements: "{{ install_path }}/{{ project_name }}/app/requirements.txt"
        virtualenv: "{{ install_path }}/{{ project_name }}/env"
        virtualenv_python: pypy
      notify:
      - restart gunicorn

    - name: make sure nginx server is running
      systemd: name=nginx state=started enabled=yes

    - name: make sure gunicorn server is running
      systemd: name=gunicorn state=started enabled=yes
    
    - name: make sure huey consumer is running
      systemd: name=huey state=started enabled=yes

  handlers: 
    - name: restart nginx
      systemd: name=nginx state=restarted

    - name: restart gunicorn
      systemd: name=gunicorn state=restarted
    
    - name: restart huey
      systemd: name=huey state=restarted
